<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT  (0.00)_hrefUserIcon</name>
   <tag></tag>
   <elementGuidId>4266649e-47e8-4cd7-ac85-35e3efef686c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hrefUserIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hrefUserIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc88c51e-b943-435e-934e-ab551012b599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrefUserIcon</value>
      <webElementGuid>4b8fae9e-8ade-4f5c-aaff-a7187ef8c6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>USER</value>
      <webElementGuid>e59bff7c-20f0-41db-8c5b-9eda0d65b89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrefUserIcon&quot;)</value>
      <webElementGuid>ffc16e9e-fcaa-4ca6-802e-2efc06f60509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hrefUserIcon']</value>
      <webElementGuid>11b48a2a-7ad0-4ec6-a8f0-b3a38cbab151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/a</value>
      <webElementGuid>2d5d9c5a-f01c-4dff-97f1-732b9f7164dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[2]</value>
      <webElementGuid>d82f026f-05d6-4307-90e5-66bb5d8dbb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::a[1]</value>
      <webElementGuid>3216fa31-377a-46e9-b75e-a86d02098a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::a[1]</value>
      <webElementGuid>cb00ed70-e4eb-4c19-a516-ad355c596ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/a</value>
      <webElementGuid>879b691d-20e0-4ba0-97ed-b1535e7de8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'hrefUserIcon' and @title = 'USER']</value>
      <webElementGuid>ac3c4320-1471-459d-882e-20598c47b7d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
