<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT  (3,027.00)</name>
   <tag></tag>
   <elementGuidId>75e22d88-77c0-41e1-ac7e-246fc27ffc84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutPopUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutPopUp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfff9719-1f55-4ac0-a2bb-efd49b8bc866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutPopUp</value>
      <webElementGuid>6a8f1c82-01aa-4e4e-b694-975ea08615ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>bd1c42af-2a88-44ed-b96d-c9f997d08094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aae3f44-a661-45fe-9928-bfe0a4252238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-binding</value>
      <webElementGuid>11c98d6f-fdc2-43fa-9457-252e0013dc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout($event)</value>
      <webElementGuid>0c66618d-05f8-47be-afb0-26d0a6b8871d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT  ($3,027.00)</value>
      <webElementGuid>281a5882-c700-4618-a52e-fe58f96232b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutPopUp&quot;)</value>
      <webElementGuid>5f8493e1-a40f-425d-98b2-02a7b7910b53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutPopUp']</value>
      <webElementGuid>b0dcef98-7ba9-4de9-9a46-7f15242bec53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tool-tip-cart[@id='toolTipCart']/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>da509e94-6b4b-44d9-8788-4c237b01f627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,027.00'])[2]/following::button[1]</value>
      <webElementGuid>f2c9f0ab-e17c-4927-8aa9-8fb924bbe98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3 Items)'])[1]/following::button[1]</value>
      <webElementGuid>7385e0fe-ab2c-4cda-bba5-d636f193123a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::button[1]</value>
      <webElementGuid>958fac65-bb4b-4c16-9f47-cf125ed3b8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::button[1]</value>
      <webElementGuid>30cd0700-36d0-4814-a757-2fbd1e9f5950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>d60fe01c-ce92-4bcc-a523-32d93bba5c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutPopUp' and @name = 'check_out_btn' and (text() = 'CHECKOUT  ($3,027.00)' or . = 'CHECKOUT  ($3,027.00)')]</value>
      <webElementGuid>b724de79-de66-4856-a83c-265efc1d5886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
