<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY NOW</name>
   <tag></tag>
   <elementGuidId>e28c5a43-bcbd-4ff6-b0b4-4e04c7daf947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay_now_btn_MasterCredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay_now_btn_MasterCredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be4bc659-4440-41f9-9d4f-62f47e2bf3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_now_btn_MasterCredit</value>
      <webElementGuid>8652997f-0d32-4781-9c3e-f52f461cb969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ec65e0c-5e63-428e-a21f-096171e6f819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium float-button a-button ng-binding</value>
      <webElementGuid>e5a04313-7ae5-417e-a1e8-baddc34d1cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f202538-baac-4b18-b7d8-ee3d0a406a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>payNow_manual()</value>
      <webElementGuid>dd268c18-645c-4651-829e-fe737fca6c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAY NOW</value>
      <webElementGuid>98aafc69-af61-457c-aef1-e726ef54fffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_now_btn_MasterCredit&quot;)</value>
      <webElementGuid>e05ffd05-20fd-49ff-b603-86fd1d5fe484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pay_now_btn_MasterCredit</value>
      <webElementGuid>5ed4aa06-7307-4595-96a9-a1e04c9b415e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_MasterCredit']</value>
      <webElementGuid>196450a2-8f07-42f2-8eab-4b63e2ba47a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[3]/div[2]/label/button</value>
      <webElementGuid>86e6c663-1806-413a-a3fe-289fbbdc8924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[2]/following::button[1]</value>
      <webElementGuid>0a0e402b-819e-4a36-893b-a087b5b63a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[1]</value>
      <webElementGuid>dc60e08b-4cde-43c6-921a-484418c2622e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice'])[2]/preceding::button[1]</value>
      <webElementGuid>847467a3-4a5b-4a10-a53e-7e514f1935ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::button[1]</value>
      <webElementGuid>54db899e-61b8-4550-ae93-88ee943afd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button</value>
      <webElementGuid>c489cad2-4063-414b-b6d9-085c3e6d8fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_MasterCredit' and @name = 'pay_now_btn_MasterCredit' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>5ef79458-fb4c-4856-8d5c-ef602c0b4751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_ManualPayment']</value>
      <webElementGuid>76a3660c-1b64-4553-8e18-a2b13a314a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div[4]/label/sec-sender/button</value>
      <webElementGuid>be18d35b-d920-4f03-bada-ff29e20fdb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[3]/following::button[1]</value>
      <webElementGuid>e6b60613-1afa-41c5-a83e-0d181295e0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes in profile for future use'])[3]/following::button[1]</value>
      <webElementGuid>7b691016-9c54-46d8-b548-a6ce6ee4a168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER SUMMARY'])[1]/preceding::button[1]</value>
      <webElementGuid>f9d2bd12-543b-4c64-a495-6878a59d3cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT'])[1]/preceding::button[1]</value>
      <webElementGuid>29447833-783c-4d0d-92b2-6e31b5907d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/sec-sender/button</value>
      <webElementGuid>7d600a82-f8ca-40e0-a870-5fcd3108ffbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_ManualPayment' and @type = 'button' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>8043f6e1-537d-4f3e-b107-a896cee35425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
