<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quantity_plus</name>
   <tag></tag>
   <elementGuidId>a2271d6a-ddb8-4d97-9927-69eefcaa2b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>477ac5a6-9d71-46e3-866b-dcf3b71aea9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>2cf8b9ae-ba1d-4f89-b77c-d84d89493078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>increment-value-attr</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>f32542f8-9aac-4d66-aa71-7480dc8fb1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;smoolMargin&quot;]/e-sec-plus-minus[@class=&quot;ng-isolate-scope sec-plus-minus&quot;]/div[@class=&quot;e-sec-plus-minus&quot;]/div[@class=&quot;plus&quot;]</value>
      <webElementGuid>ba11fe90-030f-46bd-9743-78a5cdceb0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div[2]/e-sec-plus-minus/div/div[3]</value>
      <webElementGuid>67b67d38-e4d0-492b-815d-23645e359bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//e-sec-plus-minus/div/div[3]</value>
      <webElementGuid>b2cd66f9-889d-4766-9250-dff3c6925920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
